### ISSUE TITLE
Can't use any format on Joi.date().format

### ISSUE THREAD

**Issue by danfsd** [hapijs/joi-date#28]
#### Support plan

* *Community*
* *Yes*
* *No*

#### Context

* *12.16.3*: 
* *2.0.1*: 
* *browser*
* *react-hook-form*

#### How can we help?

I am getting the following error with ANY format that I pass:
> Error: Unknown date format "MM/YYYY".

I also tried using other format such as `YYYY-MM-DD`, `DD/MM/YYYY` and many others, but the same problem occurs.

I don't know if it's relevant but I am also using moment.js in my project, on version `2.25.3`.

```js
import Joi from '@hapi/joi'
import JoiDate from '@hapi/joi-date'
Joi.extend(JoiDate)
Joi.date().format('MM/YYYY') // This is where the problem is happening
```

**Comment by Marsup** [comment]
As mentioned in the usage of the lib and in joi's API, `extend` creates a new instance of joi, it doesn't alter the existing one. Use the result of `extend`.

**Comment by danfsd** [comment]
Thanks for the tip. Issue solved.

**Comment by dale-waterworth** [comment]
Just for clarity:

```
import DateExtension from '@joi/date';
import * as JoiImport from 'joi';
const Joi = JoiImport.extend(DateExtension);
```

**Comment by salv0** [comment]
Leaving this here for anyone else in need:
When using Typescript the solution posted by @dale-waterworth  above will work but will also break the autocomplete and type information (because `JoiImport.extend(DateExtension)` returns `any`).

To make it work with typing you can simply use the following:
`const Joi = JoiImport.extend(DateExtension) as typeof JoiImport;`


Full example:
```
import DateExtension from '@joi/date';
import JoiImport from 'joi';

const Joi = JoiImport.extend(DateExtension) as typeof JoiImport;
```
